apiVersion: v1
kind: Pod
metadata:
  name: static-web-new
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: httpd
      ports:
        - name: web
          containerPort: 80
          protocol: TCP